const PARAMETROS = {
  revista: 'https://beertual.pythonanywhere.com',
};

let ARTICLE = {
  ARTICULOS_PORTADA: 'ARTICULOS_PORTADA',
  GET_ARTICULOS_PORTADA: 'GET_ARTICULOS_PORTADA',
  //Traer los articulos que no estan en portada
  GET_ARTICULOS_PORTADA_FALSE: 'GET_ARTICULOS_PORTADA_FALSE',
  OBTENER_ARTICULOS_PORTADA_FALSE: ' OBTENER_ARTICULOS_PORTADA_FALSE',

  GET_ARTICULOS_CATEGORIA:'GET_ARTICULOS_CATEGORIA',
  PUT_ARTICULOS_CATEGORIA:'PUT_ARTICULOS_CATEGORIA'
};

let ESTADISTICA = {
  GETCONFIGURACION_ESTADISTICA: 'GETCONFIGURACION_ESTADISTICA',
  OBTENERCONFIGURACION_ESTADISTICA: 'OBTENERCONFIGURACION_ESTADISTICA',
};

let CONFIGURACION_INICIAL={
  GET_CONFIGURACIONES:'GET_CONFIGURACIONES',
  PUT_CONFIGURACIONES:'PUT_CONFIGURACIONES'
}

let CONSTANTES = Object.assign(PARAMETROS, ARTICLE, ESTADISTICA, CONFIGURACION_INICIAL);

export default CONSTANTES;
