let ARTICLE = {
    ARTICULOS_PORTADA:'ARTICULOS_PORTADA'
}
let ESTADISTICA={
    GETCONFIGURACION_ESTADISTICA: 'GETCONFIGURACION_ESTADISTICA',
    OBTENERCONFIGURACION_ESTADISTICA: 'OBTENERCONFIGURACION_ESTADISTICA',
}


let CONSTANTES = Object.assign(ARTICLE, ESTADISTICA);

export default CONSTANTES;